spring:
  security:
    oauth2:
      client:
        registration:
          tidsreg:
            client-id: "tidsreg"
            client-secret: ""
            scope:
              - "openid"
              - "offline_access"
            authorization-grant-type: "authorization_code"
        provider:
          tidsreg:
            issuer-uri: "https://oidc.hosted.trifork.com/auth/realms/trifork"
management:
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    org:
        springframework:
          web:
           client:
            RestTemplate: 'DEBUG'
        ws:
          client:
            MessageTracing:
              sent: 'INFO'
              received: 'INFO'
    com:
      trifork:
        trireg: 'INFO'
server:
  port: 8080
time-registration:
  scheme: "https"
  hostname: "trireg2.tcs.trifork.dev"
  port: 443
  version: ""
  interceptor:
    logging: true
#time-registration:
#  scheme: "http"
#  hostname: "localhost"
#  port: 8080
#  version: ""
#  interceptor:
#    logging: true
springdoc:
  api-docs:
    enabled: true
    path: "/api-docs"
  swagger-ui:
    enabled: true
    path: "/api-ui"
